<?php if ($this->post) : ?>
<?php
$this->headTitle($this->post->title);
$this->layout()->pageTitle = $this->post->title;

//$this->layout()->breadcrumb = $this->widget('content','breadcrumb',array('category_id'=>$this->category->category_id));
?>

<div class="entry">
	<?php if ($this->post->image) : ?>
	<a href="<?php echo $this->post->image; ?>" class="colourbox-image cboxElement"><?php echo $this->htmlImg($this->post->image,array('mode'=>'crop','size'=>'630x276'));?></a>
	<?php endif; ?>
	
	<h2><?php echo $this->post->title; ?></h2>	
	<cite><?php echo $this->post->author; ?> - <?php echo date($this->globalConfig('web')->datetime->format->datetime, strtotime($this->post->created_date)); ?></cite>
	
	<div class="content"><?php echo $this->post->content; ?></div>
</div>
<?php endif; ?>