<?php
$this->headTitle($this->translate('Search results'));
$this->layout()->pageTitle = $this->translate('Search results');
?>

<?php foreach ($this->articles as $index => $article) : ?>
<div class="post"> 
	<div class="entry">							

		<div> 
			<h2 class="blogroll_header"><a class="blog_title" href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><?php echo $article->title; ?></a></h2>	
				<p><?php echo $article->description; ?></p> 
				<br class="clear" /> 								
		</div>  
	</div><!-- /entry --> 						
</div><!-- /post --> 
<?php endforeach; ?>

<div class="paginator">
	<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
</div>
