<?php
$this->headTitle($this->translate('Faq'));
?>
<?php if ($this->categories) {?>
<div class="node n-faq">
	<div class="title"><?php print $this->translate('Faq');?></div>
	<?php foreach ($this->categories as $cat) {?>
	<div class="row">
			<?php foreach ($this->questions[$cat->category_id] as $q){?>
            <div class="faq">
            	<div>&nbsp;
                <div class="quies">
                    <div id="number" class="FRight">Q</div>
                    <p class="FRight"><?php echo $q->question;?></p>
                </div>
                
                <div class="responce"><?php echo $q->answer;?></div>
                
                <div class="FClear"></div>
                </div>
			</div>
			<?php }?>				
	</div>
	<?php }?>
    
	<div class="node n-faq-form" align="right">
	<?php if ($this->form) {?>
		<?php echo $this->form;?>
	<?php }?>
	</div>
    
</div>
<?php }?>