<?php
$this->headTitle($this->translate($this->formDetail->title));
$this->headLink()->appendStylesheet($this->APP_URL . 'css/mainPaneFaq.css')
->appendStylesheet ($this->APP_URL.'css/twice-style.css');

 $twice_style='';
if($this->APP_LANG_ISRTL) $twice_style="twice-style-rtl"; else $twice_style="twice-style-ltr";
?>

<?php if ($this->formDetail == null) {?>
<h1><?php echo $this->translate('Form you request not found  or maybe deactivated!!!');?></h1>
<?php } else { ?>

<?php echo $this->viewMessenger(); ?>

<div class="node n-faq">
<div class="<?php print $twice_style;?> title"><?php print $this->translate($this->formDetail->title);?></div>
	<div class="n-faq-form" align="right">
	<form id="signup_form" method="post" action="<?php echo $this->formAction;?>">
		<?php foreach ($this->formFields as $field) { ?>
			<?php echo $this->formsElement($field); ?>
		<?php } ?>
	</form>
    </div>
</div>
				   	
<?php } ?>				
