<?php
$this->headTitle($this->translate($this->formDetail->page_title));
$this->headLink()
	 ->appendStylesheet($this->APP_URL . 'css/mainPaneFaq.css')
	 ->appendStylesheet ($this->APP_URL.'css/twice-style.css')
;
?>

<?php if ($this->formDetail == null) {?>
<h1><?php echo $this->translate('Form you request not found  or maybe deactivated!!!');?></h1>
<?php } else { ?>

<?php echo $this->viewMessenger(); ?>

<div class="entry">	
	<?php echo $this->formDetail->description;?>
	<div id="note"></div> 
	
	<?php echo $this->form;?>						
</div>
   	
<?php } ?>				
