	<!-- HEADER BEGIN -->
	<div id="header">
		<div class="inner">
			<div class="section_top">
				<div class="block_top_text">
					<p>WebSplash - number one in business</p>
				</div>
				<div class="block_search">
					<div id="search_show" class="button">Search</div>
					<div id="search_form_block" class="form_wrapper">
						<div class="form">
							<form action="#">
								<div class="field">
									<input type="text" class="w_def_text" title="Site search" />
								</div>
								<input type="submit" class="button" value="Search" />
							</form>
						</div>
					</div>
				</div>
				<div class="block_top_lnks">
					<ul>
						<li><a href="#sign_popup" name="sign_pop" rel="prettyPhoto[gallery0]">Sign in</a></li>
						<li><a href="#reg_popup" name="reg_pop" rel="prettyPhoto[gallery00]">Registration</a></li>
					</ul>
				</div>
			</div>
			<div class="section_bottom">
				<div id="title_top">
					<p><a href="home.html"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/spacer.gif" alt="WebSplash" title="WebSplash" /></a></p>
				</div>
				<div id="main_menu">
					<ul>
						<li class="active"><a href="home.html">Home</a>
							<ul>
								<li><a href="home.html">Home page</a></li>
								<li><a href="alternative_home_page.html">Alternative Layout</a></li>
							</ul>
						</li>
						<li><a href="slider_accordion.html">Sliders</a>
							<ul>
								<li><a href="home.html">Basic slider</a></li>
								<li><a href="slider_nivo.html">Nivo slider</a></li>
								<li><a href="slider_thumbnail.html">Thumbnail slider</a></li>
								<li><a href="slider_accordion.html">Accordion slider</a></li>
								<li><a href="slider_right.html">Right Slider</a></li>
								<li><a href="slider_3d.html">3D slider</a></li>
							</ul>
						</li>
						<li><a href="additional_elements.html">Features</a>
							<ul>
								<li><a href="pricing_table.html">Pricing table</a></li>
								<li><a href="additional_elements.html">Additional elements</a></li>
								<li><a href="columns.html">Columns</a></li>
								<li><a href="services.html">Services</a></li>
								<li><a href="archives.html">Archives</a></li>
								<li><a href="404.html">Page 404</a></li>
							</ul>
						</li>
						<li><a href="portfolio_2c.html">Portfolio</a>
							<ul>
								<li><a href="portfolio_2c.html">Portfolio 2 columns</a></li>
								<li><a href="portfolio_3c.html">Portfolio 3 columns</a></li>
								<li><a href="portfolio_4c.html">Portfolio 4 columns</a></li>
								<li><a href="portfolio_with_sidebar_2c.html">Portfolio With Right Sidebar</a>
									<ul>
										<li><a href="portfolio_with_sidebar_2c.html">2 Columns Right Sidebar</a></li>
										<li><a href="portfolio_with_sidebar_3c.html">3 Columns Right Sidebar</a></li>
									</ul>
								</li>
								<li><a href="portfolio_with_link_2c.html">Portfolio With Link Button</a>
									<ul>
										<li><a href="portfolio_with_link_2c.html">2 Columns With Link Button</a></li>
										<li><a href="portfolio_with_link_3c.html">3 Columns With Link Button</a></li>
										<li><a href="portfolio_with_link_4c.html">4 Columns With Link Button</a></li>
									</ul>
								</li>
								<li><a href="portfolio_gallery.html">Portfolio Gallery Style </a>
									<ul>
										<li><a href="portfolio_gallery.html">Gallery With Right Sidebar</a></li>
										<li><a href="portfolio_gallery_full.html">Galley Full Width</a></li>
									</ul>
								</li>
								<li><a href="portfolio_item.html">Portfolio Item Page</a></li>
							</ul>
						</li>
						<li><a href="blog_1.html">Blog</a>
							<ul>
								<li><a href="blog_1.html">Blog Style 1</a></li>
								<li><a href="blog_2.html">Blog Style 2</a></li>
								<li><a href="blog_right_1.html">Blog Style 3</a></li>
								<li><a href="blog_right_2.html">Blog Style 4</a></li>
								<li><a href="blog_right_3.html">Blog Style 5</a></li>
								<li><a href="blog_full_width.html">Blog full width</a></li>
								<li><a href="blog_post.html">Blog post page</a></li>
							</ul>
						</li>
						<li><a href="about.html">About</a></li>
						<li><a href="contact.php.html">Contact</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- HEADER END --> 