<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link rel="icon" type="image/x-icon" href="<?php echo $this->layout()->getUrl();?>/favicon.ico" />
<link rel="shortcut icon"  href="<?php echo $this->layout()->getUrl();?>/favicon.ico" type="image/x-icon"  />
<link href='http://fonts.googleapis.com/css?family=Droid+Serif:400italic|Oswald' rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="<?php echo $this->layout()->getUrl();?>/layout/style.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->layout()->getUrl();?>/layout/themes/theme_style.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->layout()->getUrl();?>/layout/plugins_styles/nivo-slider.css" type="text/css"/><!-- Necessary for Nivo slider -->
<link rel="stylesheet" href="<?php echo $this->layout()->getUrl();?>/layout/plugins_styles/prettyPhoto.css" type="text/css"/><!-- Necessary for Popups -->

<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/main.js"></script>

<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/cycle.js"></script><!-- Necessary for side slider -->
<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/slider_side.js"></script>

<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/jquery.carouFredSel-5.1.0-packed.js"></script><!-- Necessary for project carousel -->
<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/project_carousel.js"></script>

<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/jquery.prettyPhoto.js"></script><!-- Necessary for Popups -->
<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/popups.js"></script>

<!--  
<script type="text/javascript" src="layout/js/jquery.cookie.js"></script>
<script type="text/javascript" src="layout/js/theme_settings.js"></script>
-->

</head>


<body id="<?php echo $this->layout()->getParam('theme');?>" 
	  class="<?php echo $this->layout()->getParam('schemes'); ?>"
	  skin_color="<?php echo $this->layout()->getParam('schemes'); ?>"
>

<div class="pattern"></div>
<div class="main_bg"></div>
<div class="wrapper">
    	
    	<?php echo $this->layout()->render('_header');?>
        
        <!-- CONTENT BEGIN -->
        <div id="content">
        	<div class="inner">
            	<div class="block_content_top">
                	<div class="block_page_title">
                    	<p class="title">Pricing Table</p>
                        <p class="subtitle">This is a custom subpage description.</p>
                    </div>
                    
                    <div class="block_back"><p><a href="home.html">Back to Home Page »</a></p></div>
                </div>
                
                <div class="separator_10"></div>
                
                <div class="block_typography">
                	
                	<?php echo $this->layout()->content;?>
                	
                </div>
                
        	</div>
        </div>
        <!-- CONTENT END -->
        
        <?php echo $this->layout()->render('_footer');?>
        
</div>

<?php echo $this->layout()->render('_signform');?>
	
<!--  
<div class="theme_settings_wrapper">
	<a href="javascript:void(0)" id="show_settings_button"></a>
	<div class="theme_settings_container">
		<div class="theme_settings_container_top"></div>
		<div class="theme_settings_container_bott"></div>
		<a href="javascript:void(0)" id="hide_settings_button"></a>
		<h3>General skins</h3>
		<select id="skin_type">
			<option value="theme_clean">Clean theme</option>
			<option value="theme_light">Light theme</option>
			<option value="theme_dark">Dark theme</option>
		</select>
		<h3>Background</h3>
		<select id="skin_bg">
			<option value="stretched">Stretched</option>
			<option value="boxed">Boxed</option>
		</select>
		<h3>Color schemes</h3>
		<ul id="color_scheme">
			<li><a href="javascript:void(0)" id="blue" title="Blue">Blue</a></li>
			<li><a href="javascript:void(0)" id="orange" title="Orange">Orange</a></li>
			<li><a href="javascript:void(0)" id="red" title="Red">Red</a></li>
			<li><a href="javascript:void(0)" id="green" title="Green">Green</a></li>
			<li><a href="javascript:void(0)" id="dark_blue" title="Dark Blue">Dark Blue</a></li>
			<li><a href="javascript:void(0)" id="sea_wave" title="Sea Wave">Sea Wave</a></li>
			<li><a href="javascript:void(0)" id="purple" title="Purple">Purple</a></li>
			<li><a href="javascript:void(0)" id="dark_green" title="Dark Green">Dark Green</a></li>
		</ul>
		<div class="boxes_bg">
			<h3>Background Patterns</h3>
			<ul id="pattern_scheme">
				<li><a href="javascript:void(0)" id="wide_cells" title="Wide Cells">Wide Cells</a></li>
				<li><a href="javascript:void(0)" id="wide_diagonal_cells" title="Wide Diagonal Cells">Wide Diagonal Cells</a></li>
				<li><a href="javascript:void(0)" id="huge_cells" title="Huge Cells">Huge Cells</a></li>
				<li><a href="javascript:void(0)" id="diagonal_cells" title="Diagonal cells">Diagonal cells</a></li>
				<li><a href="javascript:void(0)" id="vertical_lines" title="Vertical Lines">Vertical Lines</a></li>
				<li><a href="javascript:void(0)" id="cells" title="Cells">Cells</a></li>
				<li><a href="javascript:void(0)" id="wood" title="Wood [light &amp; clean themes]">Wood [light &amp; clean themes]</a></li>
			</ul>
		</div>
		<h3>Heading Font</h3>
		<select id="skin_font">
			<option value="font_arial">Arial</option>
			<option value="font_droidsans">DroidSans</option>
			<option value="font_oswald">Oswald</option>
			<option value="font_ptsansnarrow">PTSans Narrow</option>
			<option value="font_opensanssemi">OpenSans</option>
		</select>
		<a href="javascript:void(0)" id="reset_styles">Reset styles</a>
	</div>	
</div>
-->
</body>
</html>
