<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link rel="icon" type="image/x-icon" href="favicon.ico" />
<link rel="shortcut icon"  href="<?php echo $this->layout()->getUrl();?>/favicon.ico" type="image/x-icon"  />
<link href='http://fonts.googleapis.com/css?family=Droid+Serif:400italic|Oswald' rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="<?php echo $this->layout()->getUrl();?>/layout/style.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->layout()->getUrl();?>/layout/themes/theme_style.css" type="text/css"/>
<link rel="stylesheet" href="<?php echo $this->layout()->getUrl();?>/layout/plugins_styles/prettyPhoto.css" type="text/css"/>
<!-- Necessary for Popups -->
<link rel="stylesheet" href="<?php echo $this->layout()->getUrl();?>/layout/plugins_styles/slider.css" type="text/css"/>
<!-- Necessary for Brilliant slider -->

<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/jquery-ui-1.8.16.custom.min.js"></script>
<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/slider.js"></script><!-- Necessary for brilliant slider -->
<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/jquery.carouFredSel-5.1.0-packed.js"></script><!-- Necessary for project carousel -->
<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/project_carousel.js"></script>
<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/jquery.prettyPhoto.js"></script><!-- Necessary for Popups -->
<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/popups.js"></script>
<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/main.js"></script>

<!--  
<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->layout()->getUrl();?>/layout/js/theme_settings.js"></script>
-->

</head>

<body id="<?php echo $this->layout()->getParam('theme');?>" 
	  class="brillant_blue <?php echo $this->layout()->getParam('schemes'); ?>"
	  skin_color="<?php echo $this->layout()->getParam('schemes'); ?>"
>

<div class="pattern"></div>
<div class="main_bg"></div>
<div class="wrapper">

	<?php echo $this->layout()->render('_header');?>
		
	<!-- CONTENT BEGIN -->
	<div id="content">
		<div class="inner">
			<div class="block_content_top">
				<div class="block_content_top_left"></div>
				<div class="block_slider">
					<div class="slider_wrapper">
						<ul id="slider" class="slider_cont">
							<li>
								<div class="slider_thumbs"><img src="<?php echo $this->layout()->getUrl();?>/images/78x46/pic_78x46_1.jpg" alt="" /></div>
								<div class="slider_preview"><img src="<?php echo $this->layout()->getUrl();?>/images/929x295/pic_929x295_1.jpg" alt="" /></div>
								<div class="slider_title">labore et dolore magnam</div>
								<div class="slider_details">
									Tempora incidunt ut labore et dolore magnam...
									<a href="#"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow-white.png" alt="" /></a>
								</div>
							</li>
							<li>
								<div class="slider_thumbs"><img src="<?php echo $this->layout()->getUrl();?>/images/78x46/pic_78x46_7.jpg" alt="" /></div>
								<div class="slider_preview"><img src="<?php echo $this->layout()->getUrl();?>/images/929x295/pic_929x295_7.jpg" alt="" /></div>
								<div class="slider_title">labore et dolore magnam</div>
								<div class="slider_details">
									Tempora incidunt ut labore et dolore magnam...
									<a href="#"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow-white.png" alt="" /></a>
								</div>
							</li>
							<li>
								<div class="slider_thumbs"><img src="<?php echo $this->layout()->getUrl();?>/images/78x46/pic_78x46_3.jpg" alt="" /></div>
								<div class="slider_preview"><img src="<?php echo $this->layout()->getUrl();?>/images/929x295/pic_929x295_3.jpg" alt="" /></div>
								<div class="slider_title">labore et dolore magnam</div>
								<div class="slider_details">
									Tempora incidunt ut labore et dolore magnam...
									<a href="#"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow-white.png" alt="" /></a>
								</div>
							</li>
							<li>
								<div class="slider_thumbs"><img src="<?php echo $this->layout()->getUrl();?>/images/78x46/pic_78x46_4.jpg" alt="" /></div>
								<div class="slider_preview"><img src="<?php echo $this->layout()->getUrl();?>/images/929x295/pic_929x295_4.jpg" alt="" /></div>
								<div class="slider_title">labore et dolore magnam</div>
								<div class="slider_details">
									Tempora incidunt ut labore et dolore magnam...
									<a href="#"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow-white.png" alt="" /></a>
								</div>
							</li>
							<li>
								<div class="slider_thumbs"><img src="<?php echo $this->layout()->getUrl();?>/images/78x46/pic_78x46_5.jpg" alt="" /></div>
								<div class="slider_preview"><img src="<?php echo $this->layout()->getUrl();?>/images/929x295/pic_929x295_5.jpg" alt="" /></div>
								<div class="slider_title">labore et dolore magnam</div>
								<div class="slider_details">
									Tempora incidunt ut labore et dolore magnam...
									<a href="#"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow-white.png" alt="" /></a>
								</div>
							</li>
							<li>
								<div class="slider_thumbs"><img src="<?php echo $this->layout()->getUrl();?>/images/78x46/pic_78x46_6.jpg" alt="" /></div>
								<div class="slider_preview"><img src="<?php echo $this->layout()->getUrl();?>/images/929x295/pic_929x295_6.jpg" alt="" /></div>
								<div class="slider_title">labore et dolore magnam</div>
								<div class="slider_details">
									Tempora incidunt ut labore et dolore magnam...
									<a href="#"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow-white.png" alt="" /></a>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="line_1"></div>
			<div class="separator_2"></div>
			<div class="block_slogan">
				<p>WebSplash! is a business Premium HTML Theme suitable for <span>business, portfolio</span> and any kind of websites.</p>
				<p>This theme provides all the main functionality you will need to present your product.</p>
			</div>
			<div class="separator_2"></div>
			<div class="line_1"></div>
			<div class="block_buy">
				<div class="button"><a href="#" class="general_button_1">Purchase it only for $15</a></div>
				<div class="text">
					<p>Web Solution is a business, portfolio theme available in dark and light version that is easy customizable.</p>
				</div>
			</div>
			<div class="line_1"></div>
			<div class="separator_6"></div>
			<div class="block_two_columns">
				<div class="column_1 fl">
					<h2>What we do</h2>
					<p>Long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem.</p>
					<p class="text_w_space"><a href="#" class="lnk_w_arrow_general">Read more</a></p>
				</div>
				<div class="column_2 separated_border_left fr">
					<div class="block_three_columns_type_3">
						<div class="column_narrow">
							<div class="block_services">
								<div class="pic"><img src="<?php echo $this->layout()->getUrl();?>/images/icons/icon_display.png" alt="" /></div>
								<h3>Established fact that.</h3>
								<h4>Long established that a reader.</h4>
								<div class="cl"></div>
								<p>Long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that. Has a more-or-less normal.</p>
							</div>
						</div>
						<div class="column_narrow">
							<div class="block_services">
								<div class="pic">
									<div class="separator_7"></div>
									<img src="<?php echo $this->layout()->getUrl();?>/images/icons/icon_earth.png" alt="" /></div>
								<h3>Readable content</h3>
								<h4>Variations of passages available.</h4>
								<div class="cl"></div>
								<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which.</p>
							</div>
						</div>
						<div class="column_narrow">
							<div class="block_services">
								<div class="pic"><img src="<?php echo $this->layout()->getUrl();?>/images/icons/icon_desk.png" alt="" /></div>
								<h3>Variations of passages</h3>
								<h4>Majority have suffered.</h4>
								<div class="cl"></div>
								<p>Established fact that a reader will be distracted by the readable content page when looking at its There are many variations of passages of Lorem Ipsum available.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="separator_1"></div>
			<div class="line_1"></div>
			<div class="separator_1"></div>
			<div class="block_two_columns">
				<div class="column_1 fl">
					<h2>Recent Projects</h2>
					<p>Variations of passages of Lorem Ipsum available, but the majority suffered alteration in some form, by injected humour, or randomised.</p>
					<p class="text_w_space"><a href="#" class="lnk_w_arrow_general">View all projects</a></p>
				</div>
				<div class="column_2_2 separated_border_left_18 fr">
					<div class="block_recent_projects">
						<div id="recent_projects_pager"></div>
						<div class="block_filter">
							<ul>
								<li><a href="javascript:void(0)" title="all">All Categories</a></li>
								<li><a href="javascript:void(0)" title="webdesign">Web Design</a></li>
								<li><a href="javascript:void(0)" title="photography">Photography</a></li>
								<li><a href="javascript:void(0)" title="branding">Branding</a></li>
								<li><a href="javascript:void(0)" title="video">Video</a></li>
							</ul>
						</div>
						<div class="block_three_columns_type_2 items_carousel_1" id="block_filtered_items"> 
							<!-- 1 -->
							<div class="block_general_pic_w_desc filtering_item webdesign">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="<?php echo $this->layout()->getUrl();?>/images/900x600/preview_13.jpg" class="hover_1" rel="prettyPhoto[gallery_rec]" title="Long established fact that a reader"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_1.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							<div class="block_general_pic_w_desc filtering_item photography">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="<?php echo $this->layout()->getUrl();?>/images/900x600/preview_12.jpg" class="hover_1" rel="prettyPhoto[gallery_rec]" title="Long established fact that a reader"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_2.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							<div class="block_general_pic_w_desc filtering_item video">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="http://youtu.be/08DMQ0SV6tM" class="hover_1" rel="prettyPhoto[gallery_rec]" title="Youtube Video"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_3.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							
							<!-- 2 -->
							<div class="block_general_pic_w_desc filtering_item branding">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="<?php echo $this->layout()->getUrl();?>/images/900x600/preview_24.jpg"  rel="prettyPhoto[gallery_rec]" title="Long established fact that a reader" class="hover_1"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_4.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							<div class="block_general_pic_w_desc filtering_item photography">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="<?php echo $this->layout()->getUrl();?>/images/900x600/preview_4.jpg" rel="prettyPhoto[gallery1]" title="Long established fact that a reader" class="hover_1"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_5.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							<div class="block_general_pic_w_desc filtering_item photography">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="<?php echo $this->layout()->getUrl();?>/images/900x600/preview_22.jpg"  rel="prettyPhoto[gallery_rec]" title="Long established fact that a reader" class="hover_1"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_6.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							
							<!-- 3 -->
							<div class="block_general_pic_w_desc filtering_item webdesign">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="<?php echo $this->layout()->getUrl();?>/images/900x600/preview_25.jpg" class="hover_1" title="Long established fact that a reader" rel="prettyPhoto[gallery_rec]"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_7.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							<div class="block_general_pic_w_desc filtering_item photography">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="<?php echo $this->layout()->getUrl();?>/images/900x600/preview_1.jpg" class="hover_1" title="Long established fact that a reader" rel="prettyPhoto[gallery_rec]"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_8.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							<div class="block_general_pic_w_desc filtering_item webdesign">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="<?php echo $this->layout()->getUrl();?>/images/900x600/preview_17.jpg" class="hover_1" title="Long established fact that a reader" rel="prettyPhoto[gallery_rec]"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_9.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							
							<!-- 4 -->
							<div class="block_general_pic_w_desc filtering_item branding">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="<?php echo $this->layout()->getUrl();?>/images/900x600/preview_26.jpg" class="hover_1" title="Long established fact that a reader" rel="prettyPhoto[gallery_rec]"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_10.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							<div class="block_general_pic_w_desc filtering_item branding">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="<?php echo $this->layout()->getUrl();?>/images/900x600/preview_15.jpg"class="hover_1" title="Long established fact that a reader" rel="prettyPhoto[gallery_rec]"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_11.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							<div class="block_general_pic_w_desc filtering_item webdesign">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="<?php echo $this->layout()->getUrl();?>/images/900x600/preview_23.jpg" class="hover_1" title="Long established fact that a reader" rel="prettyPhoto[gallery_rec]"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_12.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							<!-- 5 -->
							<div class="block_general_pic_w_desc filtering_item video">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="http://youtu.be/Ma8eZjNvf0o" class="hover_1" title="YouTube Video" rel="prettyPhoto[gallery_rec]"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_13.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							<div class="block_general_pic_w_desc filtering_item branding">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="<?php echo $this->layout()->getUrl();?>/images/900x600/preview_19.jpg"class="hover_1" title="Long established fact that a reader" rel="prettyPhoto[gallery_rec]"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_14.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
							<div class="block_general_pic_w_desc filtering_item video">
								<div class="pic_wrapper"> <span class="block_general_pic"> <a href="http://vimeo.com/9076474&width=700" class="hover_1" title="Vimeo Video" rel="prettyPhoto[gallery_rec]"> <img src="<?php echo $this->layout()->getUrl();?>/images/204x125/pic_home_15.jpg" class="r_conner_pic" alt="" /> <span class="block_hover">&nbsp;</span> </a> </span> </div>
								<h3><a href="#">Image title</a></h3>
								<p class="description">Long established fact that a reader will be distracted by the readable... <a href="#" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="separator_8"></div>
			<div class="line_1"></div>
			<div class="separator_1"></div>
			<div class="block_two_columns">
				<div class="column_1 fl">
					<h2>Latest from the blog</h2>
					<p>Established fact that a reader will be distracted by the readable content of  page when looking at its layout. The point of usingthat it has.</p>
					<p class="text_w_space"><a href="blog_1.html" class="lnk_w_arrow_general">View all posts</a></p>
				</div>
				<div class="column_2_2 separated_border_left_18 fr mt_4">
					<div class="block_latest_from_blog">
						<div class="block_three_columns_type_2">
							<div class="column_narrow">
								<div class="block_general_pic_w_desc">
									<div class="pic_wrapper"> <span class="block_general_pic"> <a href="blog_post.html" class="hover_2"><img src="<?php echo $this->layout()->getUrl();?>/images/204x116/pic_home_blog_1.jpg" class="r_conner_pic" alt="" /><span class="block_hover">&nbsp;</span></a></span> </div>
									<h3><a href="blog_post.html">Content of a page when looking.</a></h3>
									<p class="info">by Admin on May 23, 2011 - 2 Comments</p>
									<p class="description">Established fact that a reader will be distracted by the readable content of a page when looking at its layout... <a href="#" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
								</div>
							</div>
							<div class="column_narrow">
								<div class="block_general_pic_w_desc">
									<div class="pic_wrapper"> <span class="block_general_pic"> <a href="blog_post.html" class="hover_2"><img src="<?php echo $this->layout()->getUrl();?>/images/204x116/pic_home_blog_2.jpg" class="r_conner_pic" alt="" /><span class="block_hover">&nbsp;</span></a></span> </div>
									<h3><a href="blog_post.html">Many variations of passages.</a></h3>
									<p class="info">by Admin on May 23, 2011 - 2 Comments</p>
									<p class="description">Established fact that a reader will be distracted by the readable content of a page when looking at its layout... <a href="#" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
								</div>
							</div>
							<div class="column_narrow">
								<div class="block_general_pic_w_desc">
									<div class="pic_wrapper"> <span class="block_general_pic"> <a href="blog_post.html" class="hover_2"><img src="<?php echo $this->layout()->getUrl();?>/images/204x116/pic_home_blog_3.jpg" class="r_conner_pic" alt="" /><span class="block_hover">&nbsp;</span></a></span> </div>
									<h3><a href="blog_post.html">Majority have suffered alteration.</a></h3>
									<p class="info">by Admin on May 23, 2011 - 2 Comments</p>
									<p class="description">Established fact that a reader will be distracted by the readable content of a page when looking at its layout... <a href="#" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="separator_8"></div>
			<div class="line_1"></div>
			<div class="separator_1"></div>
			<div class="block_three_columns_type_2">
				<div class="column_wide">
					<div class="block_about_1">
						<h2>About us</h2>
						<div class="pic_left"><img src="<?php echo $this->layout()->getUrl();?>/images/pic_laptop.png" alt="" /></div>
						<p>Long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that. Has a more-or-less normal distribution of layout. The point of using looking at its layout.</p>
						<p class="text_w_space">Reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that... <a href="about.html" class="arr_d"><img src="<?php echo $this->layout()->getUrl();?>/layout/images/arrow_1.gif" alt="" /></a></p>
						<p class="text_w_space"><a href="about.html" class="lnk_w_arrow_general">Read more</a></p>
					</div>
				</div>
				<div class="column_narrow">
					<div class="block_our_skils">
						<h2>Our skills</h2>
						<p><a href="#" class="lnk_w_arrow_1">Established fact that a reader will.</a></p>
						<div class="line_3"></div>
						<p><a href="#" class="lnk_w_arrow_1">Distracted by the readable content.</a></p>
						<div class="line_3"></div>
						<p><a href="#" class="lnk_w_arrow_1">When looking at its layout. </a></p>
						<div class="line_3"></div>
						<p><a href="#" class="lnk_w_arrow_1">Has a more-or-less normal.</a></p>
						<div class="line_3"></div>
						<p><a href="#" class="lnk_w_arrow_1">Distribution of letters, as opposed.</a></p>
						<div class="line_3"></div>
					</div>
				</div>
				<div class="column_narrow">
					<div class="block_testimonials_1">
						<h2>Clients testimonials</h2>
						<div class="testimonial">
							<p>Table content of a page when lookin at its layout. The point of using is that it has a more-or-less normal. Distrib of letters, as opposed.</p>
							<div class="arrow"></div>
						</div>
						<p class="author"><a href="#">Roman Polyarush</a>, Web Designer</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- CONTENT END --> 
	
	<?php echo $this->layout()->render('_footer');?>
	
</div>

<?php echo $this->layout()->render('_signform');?>

<!--  
<div class="theme_settings_wrapper"> <a href="javascript:void(0)" id="show_settings_button"></a>
	<div class="theme_settings_container">
		<div class="theme_settings_container_top"></div>
		<div class="theme_settings_container_bott"></div>
		<a href="javascript:void(0)" id="hide_settings_button"></a>
		<h3>General skins</h3>
		<select id="skin_type">
			<option value="theme_clean">Clean theme</option>
			<option value="theme_light">Light theme</option>
			<option value="theme_dark">Dark theme</option>
		</select>
		<h3>Background</h3>
		<select id="skin_bg">
			<option value="stretched">Stretched</option>
			<option value="boxed">Boxed</option>
		</select>
		<h3>Color schemes</h3>
		<ul id="color_scheme">
			<li><a href="javascript:void(0)" id="blue" title="Blue">Blue</a></li>
			<li><a href="javascript:void(0)" id="orange" title="Orange">Orange</a></li>
			<li><a href="javascript:void(0)" id="red" title="Red">Red</a></li>
			<li><a href="javascript:void(0)" id="green" title="Green">Green</a></li>
			<li><a href="javascript:void(0)" id="dark_blue" title="Dark Blue">Dark Blue</a></li>
			<li><a href="javascript:void(0)" id="sea_wave" title="Sea Wave">Sea Wave</a></li>
			<li><a href="javascript:void(0)" id="purple" title="Purple">Purple</a></li>
			<li><a href="javascript:void(0)" id="dark_green" title="Dark Green">Dark Green</a></li>
		</ul>
		<div class="boxes_bg">
			<h3>Background Patterns</h3>
			<ul id="pattern_scheme">
				<li><a href="javascript:void(0)" id="wide_cells" title="Wide Cells">Wide Cells</a></li>
				<li><a href="javascript:void(0)" id="wide_diagonal_cells" title="Wide Diagonal Cells">Wide Diagonal Cells</a></li>
				<li><a href="javascript:void(0)" id="huge_cells" title="Huge Cells">Huge Cells</a></li>
				<li><a href="javascript:void(0)" id="diagonal_cells" title="Diagonal cells">Diagonal cells</a></li>
				<li><a href="javascript:void(0)" id="vertical_lines" title="Vertical Lines">Vertical Lines</a></li>
				<li><a href="javascript:void(0)" id="cells" title="Cells">Cells</a></li>
				<li><a href="javascript:void(0)" id="wood" title="Wood [light &amp; clean themes]">Wood [light &amp; clean themes]</a></li>
			</ul>
		</div>
		<h3>Heading Font</h3>
		<select id="skin_font">
			<option value="font_arial">Arial</option>
			<option value="font_droidsans">DroidSans</option>
			<option value="font_oswald">Oswald</option>
			<option value="font_ptsansnarrow">PTSans Narrow</option>
			<option value="font_opensanssemi">OpenSans</option>
		</select>
		<a href="javascript:void(0)" id="reset_styles">Reset styles</a> </div>
</div>
-->
</body>
</html>
