<p <?php if ($this->element->class){?> class="<?php echo $this->element->class;?>" <?php } ?>>
  <?php 
  /**
   * Print out <lable />
   */
  ?>
  <?php echo $this->formLabel($this->element->getName(),$this->element->getLabel()); ?>
  
  <br/>
  
  <?php 
  /**
   *                                               
   * Print out form_element tag using Helpers exp. $this->formText();
   */
  ?>        
  <?php echo $this->{$this->element->helper}($this->element->getName(),$this->element->getValue(),$this->element->getAttribs()); ?>
  
  <?php 
  /**
   * Display Errors if trigred
   */
  ?>
  <?php if ($this->element->getMessages()){ ?>      
  <?php echo $this->formErrors($this->element->getMessages()) ?>
  <?php }?>
  
  <?php 
  /**
   * Dispaly form hint if availible
   */
  ?>
  <?php if ($this->element->getDescription()) {?>
  <span class="small" style="display: block;"><?php echo $this->element->getDescription() ?></span>
  <?php }?>
  
</p>