<?php
$this->element->setAttrib('autocomplete','off');
?>

<p class="field">
 <?php if ($this->element->isRequired()) { ?>
  <small>*</small>
 <?php } else { ?>
  <small>&nbsp;&nbsp;</small>
 <?php  } ?>
 
  <?php echo $this->formLabel($this->element->getName(),$this->element->getLabel());?>
 
  <span class="wpcf7-form-control-wrap">    
  <?php echo $this->{$this->element->helper}($this->element->getName(),$this->element->getValue(),$this->element->getAttribs()); ?>
  </span>
  
  <?php if ($this->element->getMessages()){ ?>
  <p style="color:red;">    
  <?php echo implode('<br/>', $this->element->getMessages()) ?>
  </p>
  <?php }?>
  
  <?php if ($this->element->getDescription()) {?>
  <span class="small" style="display: block;"><?php echo $this->element->getDescription() ?></span>
  <?php }?>
</p> 
